# java-tron FullNode - mainnet
# Full default: https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/resources/config.conf
# This file can be replaced by the full config from the repo for production.

net {
}

storage {
  db.engine = "LEVELDB"
  db.sync = false
  db.directory = "database"
  transHistory.switch = "on"
  needToUpdateAsset = true
  balance.history.lookup = false
  txCache.initOptimization = true
}

node.discovery = {
  enable = true
  persist = true
}

node.backup {
  port = 10001
  priority = 8
  keepAliveInterval = 3000
  members = []
}

crypto {
  engine = "eckey"
}

node.metrics.prometheus.enable = false

node {
  trustNode = "127.0.0.1:50051"
  walletExtensionApi = true
  listen.port = 18888
  connection.timeout = 2
  fetchBlock.timeout = 200
  maxConnections = 30
  minConnections = 8
  minActiveConnections = 3
  maxConnectionsWithSameIp = 2
  maxHttpConnectNumber = 50
  minParticipationRate = 15
  p2p {
    version = 11111
  }
  active = []
  passive = []
  fastForward = [
    "100.27.171.62:18888",
    "15.188.6.125:18888"
  ]
  http {
    fullNodeEnable = true
    fullNodePort = 8090
    solidityEnable = true
    solidityPort = 8091
    PBFTEnable = true
    PBFTPort = 8092
  }
  rpc {
    enable = true
    port = 50051
    solidityEnable = true
    solidityPort = 50061
    PBFTEnable = true
    PBFTPort = 50071
    maxConnectionIdleInMillis = 60000
    minEffectiveConnection = 1
    reflectionService = false
  }
}
